amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: "/scan"
    max_particles: 500
    min_particles: 200
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    laser_model_type: "likelihood_field"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    update_min_d: 0.2
    update_min_a: 0.5
    transform_tolerance: 0.2
    resample_interval: 1

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "/home/kingpooper/deepRacerWS/my_map.yaml"

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.26
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 5
      vtheta_samples: 5
      sim_time: 1.0
      critics: ["RotateToGoal", "GoalDist", "PathAlign"]
      RotateToGoal.scale: 1.0
      GoalDist.scale: 1.0
      PathAlign.scale: 1.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: "/home/kingpooper/deepRacerWS/src/robot_car/behavior_trees/navigate_through_poses.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: True

lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: True
    bond_timeout: 30.0
    transition_timeout: 30.0
    node_names:
      - map_server
      - amcl
      - controller_server
      - planner_server
      - bt_navigator
      - waypoint_follower
