slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: false
    mode: localization

    map_file_name: "/home/kingpooper/deepRacerWS/src/robot_car/maps/my_map"  # omit .yaml extension
    map_start_pose: [0.0, 0.0, 0.0]

    map_frame: map
    base_frame: base_footprint
    odom_frame: odom
    scan_topic: /scan

    transform_publish_period: 0.05
    resolution: 0.1     # match what you used during mapping
    minimum_time_interval: 0.2
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
